worker_processes 1;                         # Number of worker processes #worker doesnt have an ip
#worker_processes auto; can be this and nginx maintains it basis the core of the machine
#find cores of the machine - sysctl -n hw.ncpu

events {
    worker_connections 1024;               # Max connections per worker
    # accept_mutex on;   # prevents multiple workers grabbing same connection
}
#worker connection if 4 core - 4*1024

http {
    include conf.d/*.conf;                # Load route configs
}
#can have multiple *conf files in the directory owned by multiple processes.

# Request comes
# Worker starts processing
# Waits for DB/API → does NOT block
# Handles another request in meantime


# Client → hits port 8080
#         -
# OS (network stack / kernel)
#         -
# Assigns connection to a worker
#         -
# NGINX worker handles it

# Because:
# Ports (8080) are managed by OS
# Network sockets belong to OS
# NGINX runs on top of OS