worker_processes 1;                         # Number of worker processes

events {
    worker_connections 1024;               # Max connections per worker
}

http {
    include conf.d/*.conf;                # Load route configs
}