# link multiple servers to one process.
# upstream bananas {
#     server 10.0.0.1:8001;
# }
# location /profile {
#     proxy_pass http://bananas;
# }

server {
    listen 8080;                          # Gateway port

    # Internal auth validation endpoint
    location = /auth/validate { #= is exact match
        internal;                         # Cannot be accessed externally

        proxy_pass http://auth-service:8002/validate;  # Call auth service

        proxy_pass_request_body off;      # No body needed
        proxy_set_header Content-Length "";

        proxy_set_header Authorization $http_authorization; # Forward token
    }

    # 👤 Protected route
    location /profile {
        auth_request /auth/validate;      # Call auth before request

        proxy_pass http://profile-service:8001; # Forward request

        proxy_set_header Authorization $http_authorization;
    }

    # 🔓 Public auth routes
    location /auth {
        proxy_pass http://auth-service:8002;
    }
}